# Generated by Django 3.2.12 on 2022-03-12 03:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='modified date')),
                ('question_text', models.CharField(max_length=200)),
            ],
            options={
                'permissions': (('manage_questions', 'Manage questions.'),),
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='modified date')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.question')),
            ],
            options={
                'permissions': (('manage_choices', 'Manage choices.'),),
            },
        ),
    ]
